### ISSUE TITLE
why during the development process did the SCSS code changes not affect localhost:3000 ?

### ISSUE THREAD

**Issue by wahyunandanovan** [cjephuneh/car-rental-main#1]
hey, thank you in advance and it really helped me in my process of learning Reactjs + Sass. I have a question here, why during the development process did the SCSS code changes not affect localhost:3000 ?

**Comment by cjephuneh** [comment]
hey man

**Comment by cjephuneh** [comment]
share the screenshots it should

**Comment by cjephuneh** [comment]
or we can do a google meet 
calebjephuneh@gmail.com
ping me up lets discuss that

**Comment by cjephuneh** [comment]
.....................................

Caleb would like to stay in touch on LinkedIn.

Caleb Jephunneh
Software Engineer
Kenya

View profile https://www.linkedin.com/comm/in/caleb-jephunneh-a96aa81b0?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-1hr2b9%7Elkcem52y%7Efi-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BjW3pip1hR82%2BgB1d5by2Rg%3D%3D

Confirm that you know Caleb https://www.linkedin.com/e/v2?e=1hr2b9-lkcem52y-fi&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BjW3pip1hR82%2BgB1d5by2Rg%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=KL3RT3K0&invitationId=7088093546594934784


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=1hr2b9-lkcem52y-fi&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQF1xnVKlA9x6QAAAYl33sPZmobLYwRX7jDU70iOlgcWgNaO5sDJNKOc4Sz-zw-DNPwLXWbh9aatCcKVlcqPMSD_WJksZ8vw83gj_9j-pnyLAvbpF49T5sNQpC0U6xnMOzzC5Tx8Vnn0093CLCRDYIqPgw2wYcZG7w&eid=1hr2b9-lkcem52y-fi

Help: https://www.linkedin.com/e/v2?e=1hr2b9-lkcem52y-fi&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BjW3pip1hR82%2BgB1d5by2Rg%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2023 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
